### ISSUE TITLE
求数据集

### ISSUE THREAD

**Issue by F1rew0rkkk** [TangBinghao/naacl2024#1]
您好，请问可以求一下完整的数据集吗，您附在项目中的数据集似乎不完全，十分感谢

**Comment by TangBinghao** [comment]
项目中贴出的是RedEval测试集数据，训练数据可以参考
- MMSD：https://github.com/headacheboy/data-of-multimodal-sarcasm-detection
- MMSD2.0：https://github.com/joeying1019/mmsd2.0

**Comment by F1rew0rkkk** [comment]
感谢！

**Comment by F1rew0rkkk** [comment]
您好，抱歉打扰您一些时间，可否请问下您在代码中所使用的flash-attn的版本，我使用了2.3.5+cu117torch2.0cxxabiFALSE-cp310-cp310-linux_x86_64的版本，同时使用了cuda11.7，也同您在实验中一样使用了torch2.0.1版本，但遇到了疑似是不兼容的问题，可以的话可以麻烦您告知一下吗十分感谢发自我的手机-------- 原始邮件 --------发件人： TangBinghao ***@***.***>日期： 2024年10月23日周三 傍晚5:28收件人： TangBinghao/naacl2024 ***@***.***>抄送： F1rew0rkkk ***@***.***>, Author ***@***.***>主    题： Re: [TangBinghao/naacl2024] 求数据集 (Issue #1)
项目中贴出的是RedEval测试集数据，训练数据可以参考
MMSD：https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0：https://github.com/joeying1019/mmsd2.0

**Comment by believe81** [comment]
> 您好，抱歉打扰您一些时间，可否请问下您在代码中所使用的flash-attn的版本，我使用了2.3.5+cu117torch2.0cxxabiFALSE-cp310-cp310-linux_x86_64的版本，同时使用了cuda11.7，也同您在实验中一样使用了torch2.0.1版本，但遇到了疑似是不兼容的问题，可以的话可以麻烦您告知一下吗十分感谢发自我的手机-------- 原始邮件 --------发件人： TangBinghao ***@***.***>日期： 2024年10月23日周三 傍晚5:28收件人： TangBinghao/naacl2024 ***@***.***>抄送： F1rew0rkkk ***@***.***>, Author ***@***.***>主 题： Re: [TangBinghao/naacl2024] 求数据集 (Issue #1) 项目中贴出的是RedEval测试集数据，训练数据可以参考 MMSD：[https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0：https://github.com/joeying1019/mmsd2.0](https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0%EF%BC%9Ahttps://github.com/joeying1019/mmsd2.0) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

你好，我的环境也出现了问题。你环境配成功了吗，在不修改代码的情况下，各种python包的版本是怎样的呢。期待你的回复，跪谢！！！！

**Comment by F1rew0rkkk** [comment]
> > 您好，抱歉打扰您一些时间，可否请问下您在代码中所使用的flash-attn的版本，我使用了2.3.5+cu117torch2.0cxxabiFALSE-cp310-cp310-linux_x86_64的版本，同时使用了cuda11.7，也同您在实验中一样使用了torch2.0.1版本，但遇到了疑似是不兼容的问题，可以的话可以麻烦您告知一下吗十分感谢发自我的手机-------- 原始邮件 --------发件人： TangBinghao _**@**_._**>日期： 2024年10月23日周三 傍晚5:28收件人： TangBinghao/naacl2024 _**@**_.**_>抄送： F1rew0rkkk _**@**_._**>, Author _**@**_.**_>主 题： Re: [TangBinghao/naacl2024] 求数据集 (Issue #1) 项目中贴出的是RedEval测试集数据，训练数据可以参考 MMSD：[https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0：https://github.com/joeying1019/mmsd2.0](https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0%EF%BC%9Ahttps://github.com/joeying1019/mmsd2.0) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 你好，我的环境也出现了问题。你环境配成功了吗，在不修改代码的情况下，各种python包的版本是怎样的呢。期待你的回复，跪谢！！！！

你好，我的环境完全是按照作者配置文件中要求进行配置的，除了微调阶段用于加快训练进程的flash-attn库，其他配置均没有出现问题，建议你重点关注torch和cuda版本相关配置。

**Comment by believe81** [comment]
感谢❀！！！我再试一下

> > > 您好，抱歉打扰您一些时间，可否请问下您在代码中所使用的flash-attn的版本，我使用了2.3.5+cu117torch2.0cxxabiFALSE-cp310-cp310-linux_x86_64的版本，同时使用了cuda11.7，也同您在实验中一样使用了torch2.0.1版本，但遇到了疑似是不兼容的问题，可以的话可以麻烦您告知一下吗十分感谢发自我的手机-------- 原始邮件 --------发件人： TangBinghao _**@**_._**>日期： 2024年10月23日周三 傍晚5:28收件人： TangBinghao/naacl2024 _**@**_.**_>抄送： F1rew0rkkk _**@**_._**>, Author _**@**_.**_>主 题： Re: [TangBinghao/naacl2024] 求数据集 (Issue #1) 项目中贴出的是RedEval测试集数据，训练数据可以参考 MMSD：[https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0：https://github.com/joeying1019/mmsd2.0](https://github.com/headacheboy/data-of-multimodal-sarcasm-detectionMMSD2.0%EF%BC%9Ahttps://github.com/joeying1019/mmsd2.0) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 你好，我的环境也出现了问题。你环境配成功了吗，在不修改代码的情况下，各种python包的版本是怎样的呢。期待你的回复，跪谢！！！！
> 
> 你好，我的环境完全是按照作者配置文件中要求进行配置的，除了微调阶段用于加快训练进程的flash-attn库，其他配置均没有出现问题，建议你重点关注torch和cuda版本相关配置。
