### ISSUE TITLE
评测时的Template问题

### ISSUE THREAD

**Issue by believe81** [TangBinghao/naacl2024#2]
想请问作者评测大模型时，是否使用了不同的Template，不同的Template对结果影响大吗。在评测LLava时得到如下结果时，LLaVa是经过微调的嘛？
![屏幕截图 2024-11-22 192346](https://github.com/user-attachments/assets/0187be8e-f775-4a8a-ba32-6fdd4cf8fac4)

期待作者的回复，非常感谢！！！

**Comment by TangBinghao** [comment]
- Template格式整体和Base model的预训练数据格式保持一致，在输入信息完整的情况下，不同template的影响不大。
- 模型都是经过Lora微调的
