### ISSUE TITLE
关于image caption

### ISSUE THREAD

**Issue by aaron-ywl** [TangBinghao/naacl2024#3]
你好，请问image caption部分可以发出来吗？我在项目中没有看见这部分的内容 十分感谢！

**Comment by TangBinghao** [comment]
论文中使用了BLIP2-FlanT5-XL模型，Image captioning部分的代码可以参考https://huggingface.co/docs/transformers/main/en/model_doc/blip-2#transformers.Blip2ForConditionalGeneration.forward.example
